language: php

php:
  - 5.6

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --prefer-dist --no-interaction --dev

script:
 - mkdir -p build/logs
 - phpunit --verbose --debug --coverage-clover build/logs/clover.xml

after_script:
 - vendor/bin/coveralls -v